# Backend Server Service

apiVersion: v1
kind: Service
metadata:
  name: frontend-server
  namespace: lateats
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: frontend-server

---

# Backend Server Deployment

# version of object API, see "kubectl api-versions"
apiVersion: apps/v1

# type of object (Deployment)
kind: Deployment

# Dictionary of information about the object
metadata:
  name: frontend-server
  namespace: lateats

# Additional information about the object
spec:
  # desired no. of pods at all times
  replicas: 2
  # labels and selectors (e.g., env: dev)
  selector:
    # this associates the pod and the deployment
    matchLabels:
      app: frontend-server
  template:
    metadata:
      namespace: lateats
      labels:
        app: frontend-server
    spec:
      containers:
      - name: frontend-server
        image: ghcr.io/leungwj/lateats-frontend-server:latest
        ports:
        - containerPort: 5000
        command: ["npm", "start"]


